spring.application.name=student-management

spring.datasource.url=jdbc:postgresql://localhost:5432/dbName
spring.datasource.username=abcd
spring.datasource.password=abcd
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.mvc.pathmatch.matching-strategy=ant-path-matcher
